In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [3]:
#Генерим случайные данные
x = np.arange(1,11) * (100 + np.random.randn(10))
y = 2 * x + np.random.randn(10)*5
X = np.vstack((x,y))
print('Мы получили 10 объектов с 2 признаками')
print(np.transpose(X))

Мы получили 10 объектов с 2 признаками
[[ 101.75571146  199.48536483]
 [ 201.74779296  401.98054242]
 [ 300.43005022  598.1123622 ]
 [ 400.33973941  793.57163019]
 [ 503.46209035 1004.28756469]
 [ 620.76420767 1247.0770984 ]
 [ 705.85691488 1425.90476059]
 [ 784.24640268 1562.60723449]
 [ 893.53181138 1787.74301034]
 [1014.5045518  2033.63569967]]


In [ ]:
#Посчитаем прям вручную наше РСА преобразование 

In [ ]:
print('Матрица корреляции')
pd.DataFrame(np.transpose(X)).corr()

Матрица корреляции


0         1
0  1.000000  0.999965
1  0.999965  1.000000

In [8]:
#отцентрируем наши даннеы, чтобы наше мат ожидание равнялось 0

Xcentered = (X[0] - x.mean(), X[1] - y.mean())
#берем 1-й признак и вычитаем из него среднее первого признака и потом вычитаем ср значение второго признака 

m = (x.mean(), y.mean())
print('Отцентрованные признаки')
print(np.transpose(Xcentered))
print("Mean vector: ", m)
#Вектор нашего мат ожидания 

Отцентрованные признаки
[[-450.90821582 -905.95516195]
 [-350.91613432 -703.45998436]
 [-252.23387706 -507.32816459]
 [-152.32418787 -311.86889659]
 [ -49.20183693 -101.1529621 ]
 [  68.10028039  141.63657162]
 [ 153.1929876   320.4642338 ]
 [ 231.5824754   457.16670771]
 [ 340.8678841   682.30248356]
 [ 461.84062452  928.19517289]]
Mean vector:  (552.6639272806249, 1105.4405267822312)


In [9]:
covmat = np.cov(Xcentered) 
# Просчет матрици ковариации
print('Матрица ковариации')
print(covmat, "\n")
print("Variance of X: ", np.cov(Xcentered)[0,0]) #Дисперсия 1-го признака
print("Variance of Y: ", np.cov(Xcentered)[1,1]) #Диспервсия 2-го признака
print("Covariance X and Y: ", np.cov(Xcentered)[0,1]) #Ковариация между ними

Матрица ковариации
[[ 91881.06883824 184629.88061921]
 [184629.88061921 371036.58914346]] 

Variance of X:  91881.06883823659
Variance of Y:  371036.58914345864
Covariance X and Y:  184629.88061920617


In [10]:
#разложим нашу матрицу ковариации на собственные числа и векотора

le, vecs = np.linalg.eig(covmat)
# np.linalg.eig для разложения на собственныне числа и вектора 
v = vecs[:,1] 
# Берем 1 собственный вектор, для того, чтобы преобразовать наши данные   
Xnew = np.dot(np.transpose(Xcentered), v)
print(f'Матрица собственных векторов:\n{vecs}\n Собственные числа:\n{le}')
print("".join(['\n']+["-" for x in range(30)]))
print(f'Так как второе собственное число гораздо больше первого,\nто для преобразования берем второй вектор:\n{v}')
print("".join(['\n']+["-" for x in range(30)]))
print(f'Преобразованные данные:\n {np.transpose(Xnew).reshape(-1,1)}')

Матрица собственных векторов:
[[-0.89527987 -0.44550417]
 [ 0.44550417 -0.89527987]]
 Собственные числа:
[6.57917097e+00 4.62911079e+05]

------------------------------
Так как второе собственное число гораздо больше первого,
то для преобразования берем второй вектор:
[-0.44550417 -0.89527987]

------------------------------
Преобразованные данные:
 [[ 1011.96490443]
 [  786.12816014]
 [  566.57193414]
 [  347.07100416]
 [  112.47983366]
 [ -157.14332945]
 [ -355.15329041]
 [ -512.46310627]
 [ -762.70973833]
 [-1036.74637206]]


In [ ]:
print( 'Как видно, матрица корреляции диагональна\nи корреляция между признаками практически равна нулю')
pd.DataFrame(np.dot(np.transpose(Xcentered), vecs)).corr()
#Этого мы и хотели, чтобы наши преобразованнеы новые данные не имеля корреляцию 

Как видно, матрица корреляции диагональна
и корреляция между признаками практически равна нулю


0             1
0  1.000000e+00  8.985252e-16
1  8.985252e-16  1.000000e+00

In [ ]:
#Мы некоторые данные потеряли, так как отбросили один из собственных векторов

In [13]:
#Делаем обратное преобразование
#Берем вектор, который мы использовали для преобразования, используем его для новых данных и 
#прибавляем к нем соответствеющее среднее значение
print('Восстановим элементы')
_= [print('Restored: ', (np.dot(Xnew[i],v) + m),': original: ', X[:,i]) for i in range(len(Xnew))]
#Первый столбик новые данные, второй оригинальные

Восстановим элементы
Restored:  [101.82934742 199.44872252] : original:  [101.75571146 199.48536483]
Restored:  [202.44055763 401.63581274] : original:  [201.74779296 401.98054242]
Restored:  [300.25377079 598.20008138] : original:  [300.43005022 598.1123622 ]
Restored:  [398.04234934 794.7148446 ] : original:  [400.33973941 793.57163019]
Restored:  [ 502.5536929  1004.73959635] : original:  [ 503.46209035 1004.28756469]
Restored:  [ 622.67193507 1246.12778575] : original:  [ 620.76420767 1247.0770984 ]
Restored:  [ 710.88619741 1423.40211711] : original:  [ 705.85691488 1425.90476059]
Restored:  [ 780.96837559 1564.23842801] : original:  [ 784.24640268 1562.60723449]
Restored:  [ 892.45429247 1788.27919928] : original:  [ 893.53181138 1787.74301034]
Restored:  [1014.53875419 2033.61868007] : original:  [1014.5045518  2033.63569967]


In [14]:
#Теперь посчитаем не вручную, а встроенной функцией

from sklearn.decomposition import PCA

pca = PCA(n_components = 1)
#Создаем объект РСА, который приводит наши данные к 1 компаненте 
XPCAreduced = pca.fit_transform(X.T)
#используем метод fit_transform на наших данных, который возвращает нам новое представление данных 

In [15]:
XPCAreduced

array([[-1011.96490443],
       [ -786.12816014],
       [ -566.57193414],
       [ -347.07100416],
       [ -112.47983366],
       [  157.14332945],
       [  355.15329041],
       [  512.46310627],
       [  762.70973833],
       [ 1036.74637206]])

In [ ]:
#Обратите внимание что при использовании PCA собственный вектор 
#используется со знаком минус этот момент разрешен так как любая 
#линейная комбинация собственных векторов x1, x2, ..., xm, 
#отвечающих одному и тому же собственному числу λ, является собственным 
#вектором с тем же собственным числом.

In [16]:
#Разница между тем, что мы сделали вручную и встроенной функцией практически равна 0


for xn, x_pca in zip(Xnew, XPCAreduced):
    print(np.abs(xn), '-', np.abs(x_pca[0]), '=', np.abs(xn) - np.abs(x_pca[0]))

1011.964904426594 - 1011.9649044265941 = -1.1368683772161603e-13
786.1281601361918 - 786.1281601361918 = 0.0
566.5719341365657 - 566.5719341365656 = 1.1368683772161603e-13
347.0710041644786 - 347.0710041644786 = 0.0
112.4798336568708 - 112.4798336568708 = 0.0
157.1433294504109 - 157.14332945041087 = 2.842170943040401e-14
355.15329041345655 - 355.15329041345655 = 0.0
512.463106274912 - 512.463106274912 = 0.0
762.7097383256767 - 762.7097383256768 = -1.1368683772161603e-13
1036.7463720562448 - 1036.7463720562448 = 0.0


In [ ]:
#Восстанавлиеваем наши данные 
pca.inverse_transform(XPCAreduced)

array([[ 102.0261558 ,  206.95684329],
       [ 196.40369248,  395.17033941],
       [ 296.8161551 ,  595.41905654],
       [ 400.92814152,  803.04559186],
       [ 495.61520249,  991.87636039],
       [ 601.01612617, 1202.07337378],
       [ 710.89452385, 1421.19964157],
       [ 803.49478787, 1605.86879111],
       [ 901.41968878, 1801.15665947],
       [ 989.79140342, 1977.3929754 ]])

In [ ]:
#Посмотрим, какие были и какие стали 
#Восстановлени произошло достаточно близко к исходных данным 
print('Восстановим элементы')
_= [print('Restored: ', (pca.inverse_transform(XPCAreduced)[i]),': original: ', X[:,i]) for i in range(len(Xnew))]

Восстановим элементы
Restored:  [102.0261558  206.95684329] : original:  [ 98.96062377 208.49401978]
Restored:  [196.40369248 395.17033941] : original:  [197.71106274 394.51477332]
Restored:  [296.8161551  595.41905654] : original:  [300.56789197 593.53779036]
Restored:  [400.92814152 803.04559186] : original:  [399.99347248 803.51427112]
Restored:  [495.61520249 991.87636039] : original:  [494.05957612 992.6564117 ]
Restored:  [ 601.01612617 1202.07337378] : original:  [ 600.42154795 1202.37151833]
Restored:  [ 710.89452385 1421.19964157] : original:  [ 713.38001612 1419.95331948]
Restored:  [ 803.49478787 1605.86879111] : original:  [ 803.74484888 1605.74340083]
Restored:  [ 901.41968878 1801.15665947] : original:  [ 900.23019119 1801.75311964]
Restored:  [ 989.79140342 1977.3929754 ] : original:  [ 989.33664626 1977.62100825]


In [ ]:
#можно посмотреть долю покрытой дисперсии данных
#Показатель почти 1, значит практически все данные хранились в одном из признаков 
pca.explained_variance_ratio_

array([0.99998881])